[font]
size = 12.0


[font.normal]
family = "Iosevka Nerd Font"

[window]
padding = { x = 12, y = 12}
opacity = 0.95

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#140f0c'
foreground = '#bfbfbf'

# Normal colors
[colors.normal]
black   = '#140f0c'
red     = '#4b0d11'
green   = '#303f2c'
yellow  = '#442812'
blue    = '#2a2a69'
magenta = '#550029'
cyan    = '#3b4e4f'
white   = '#756661'

# Bright colors
[colors.bright]
black   = '#241d18'
red     = '#860104'
green   = '#3f4f3b'
yellow  = '#493929'
blue    = '#4d4d86'
magenta = '#701c3e'
cyan    = '#4b7a7d'
white   = '#bfbfbf'
