#!/bin/sh


# autostart
kanshi &
dunst &
dex -a &
waybar &
swaybg -i ~/.local/share/hydrus/db/client_files/f2a/2afebd334ec5e537c19dfee37f803ab20d986d854d0b2c1fd8167bb71b19ce28.jpg&
swayidle &
playerctld daemon &

riverctl map normal Super Q spawn alacritty
riverctl map normal Super E spawn thunar
riverctl map normal Super R spawn "wofi --show drun --allow-images"
riverctl map normal Super+Shift R spawn "wofi --show run"
riverctl map normal Super W spawn "shiori search"
riverctl map normal Super+Shift W spawn "shiori tag"
riverctl map normal Super+Shift S spawn "screenshot.bash region"
riverctl map normal Super S spawn "screenshot.bash temp"
riverctl map normal None Print spawn "screenshot.bash"
riverctl map normal Super+Shift W spawn "shiori tag"

# layous
riverctl map normal Super M send-layout-cmd layout.py "layout monocle"
riverctl map normal Super T send-layout-cmd layout.py "layout tile"
riverctl map normal Super+Shift T send-layout-cmd layout.py "layout row"

# Close the focused view
riverctl map normal Super+Shift C close

# Exit river
riverctl map normal Super+Shift M exit

# focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd layout.py "master-ratio -0.05"
riverctl map normal Super L send-layout-cmd layout.py "master-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd layout.py "master-count +1"
riverctl map normal Super+Shift L send-layout-cmd layout.py "master-count -1"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super B spawn "killall -SIGUSR1 waybar"

# Super+Space to toggle float
riverctl map normal Super V toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl map normal Super equal spawn 'pamixer -i 5'
riverctl map normal Super minus spawn 'pamixer -d 5'
riverctl map noraml None XF86AudioPlay  spawn 'playerctl play-pause'
riverctl map noraml None XF86AudioPause  spawn 'playerctl play-pause'
riverctl map noraml None XF86AudioPrev  spawn 'playerctl previous'
riverctl map noraml None XF86AudioNext  spawn 'playerctl next'

# Example of mode
# riverctl declare-mode passthrough
# riverctl map normal Super F11 enter-mode passthrough
# riverctl map passthrough Super F11 enter-mode normal

# Example for sharing button between mode
# for mode in normal locked
# do
#     riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
# done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x29366f 
riverctl border-color-unfocused 0x1a1c2c 

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
# Set the default layout generator to be filtile and start it.
riverctl default-layout layout.py

# - Smart gaps on the sides of every tag (on the larger monitor), to keep
#   single windows from being gigantic.
#
# - A scratch pad on tag 7 with pad (to keep the first window from resizing
#   a bunch) and giant gaps for bling. 
#
# - Tag 1 usually has a browser, which is usually easier to read when it's on
#   the right.
# filtile view-padding 0, outer-padding 0 &
layout.py &
