#!/bin/sh
xrandr --output DP-0 --scale 0.5x0.5 --filter nearest
qtile cmd-obj -o cmd -f reload_config
wine /home/nikohonu/games/BLACK\ SOULS/game.exe
xrandr --output DP-0 --scale 1x1
qtile cmd-obj -o cmd -f reload_config
