#!/bin/bash

CURRENT_PORT=$(pactl list | grep "Active Port" | head -n 1)

if [ "$CURRENT_PORT" = "	Active Port: analog-output-headphones" ]; then
  pactl set-sink-port alsa_output.pci-0000_2f_00.4.analog-stereo analog-output-lineout
else 
  pactl set-sink-port alsa_output.pci-0000_2f_00.4.analog-stereo analog-output-headphones
fi

